### PR TITLE
Ubuntu crypt xs perl clients

### PR DESCRIPTION
**Pull request by carrott**
change perl clients to use CRYPT::RC4 instead of CRYPT::RC4::XS for easier ubuntu compatibility

### CODE REVIEW

**Comment by dexterbg** [comment]
Hi carrott, thanks for contributing!

Can you please elaborate on why Crypt::RC4::XS has a compatibility problem? I'm using Ubuntu on my laptop and had no problems installing the ::XS module.

Regards,
Michael

**Comment by carrott** [comment]
Crypt::RC4 is available as an Ubuntu package via apt-get while Crypt::RC4:XS requires you to use cpan. I couldn't see any significant differences in the descriptions of these modules though I haven't looked at their source code.

If, like me, you're not a regular perl user, the packages from your distribution are going to be easier.

**Comment by dexterbg** [comment]
The difference is that ::XS is a much more efficient RC4 implementation.

While that efficiency may not be strictly required for the OVMS perl tools, I think it's generally the wrong solution to replace a module by an inferior version just because some distribution lacks a prebuilt package. The right solution would be to add the missing package to the distribution repositories.

Btw: you can easily build a debian package from any CPAN module using the dh-make-perl tool, see http://stackoverflow.com/a/75985 for a short explanation.

But I also think the standard way of installing CPAN modules is using cpan or cpanminus, as that works the same way for all perl modules on all perl platforms, no need for system specific instructions.

**Comment by markwj** [comment]
Given the 150+ times performance of Crypt::RC4::XS vs Crypt::RC4, I think it best to stick with the XS version.

I've added the following explanatory text to
[master f384e9f] Add explanatory text for Crypt::RC4::XS vs Crypt::RC4

A note on Crypt::RC4::XS
========================

There are two version of Crypt::RC4 in perl. The first is the pure perl implementation Crypt::RC4,
and the second is the C code wrapped in an XS implementation Crypt::RC4::XS.

A rough comparison:
  10,000 iterations of RC4 encryption on a block of 26KB plain text.
    Crypt::RC4         399.20 seconds
    Crypt::RC4::XS       2.54 seconds

In general, we recommend using Crypt::RC4::XS as it is significantly faster (at least 100x faster).

However, if you want to use Crypt::RC4 (the slower pure perl implementation), perhaps because
it is in your distribution and doesn't need to be installed via cpan, then you can. But change
all references to Crypt::RC4::XS to Crypt::RC4 in the perl client code.

**Comment by carrott** [comment]
Good call on keeping the XS version -- I looked at the sourcecode rather than the documentation and the XS version does look better, it even has tests!

**Pull request closed without merging**
